# This is a basic workflow to help you get started with Actions

name: Unit tests for backend API

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ${{matrix.os}}
    strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macOS-latest]
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      #Install jest
      - name: Jest for Unit testing 
        run: npm install --save-dev jest
      
      #Run the unit tests
      - name: Backend Unit Tests
        run: npx jest --runInBand db.test.js

  
